# Generated by Django 5.0.6 on 2024-06-22 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0003_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
