# Generated by Django 5.0.6 on 2024-07-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0005_alter_timetable_end_time_alter_timetable_start_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='venue',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
